name: 'Run edgetest'
description: 'Run edgetest on your Python package'
inputs:
  edgetest-flags:  # id of input
    description: 'Options to pass to edgetest'
    required: true
    default: ''
  base-branch: # branch to base PR off
    description: 'Branch to base PR off'
    required: true
    default: 'dev'
  skip-pr: # skip PR creation
    description: 'Skip submitting a PR if there are changes (boolean)'
    required: true
  python-version: # Python version to use
    description: 'Python version to use (from "setup-miniconda"). Defaults to 3.10. 
      See https://anaconda.org/anaconda/python for available "python" versions.'
    default: '3.10'
runs:
  using: "composite"
  steps:
    - run: echo Running edgetest with the following options ${{ inputs.edgetest-flags }}.
      shell: bash
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ inputs.python-version }}
        channels: conda-forge
    - name: Install edgetest edgetest-conda and edgetest-pip-tools
      shell: bash -l {0}
      run: |
        conda install edgetest edgetest-conda edgetest-pip-tools
    - name: Run edgetest
      shell: bash -l {0}
      run: |
        edgetest ${{ inputs.edgetest-flags }}
    - name: Create Pull Request
      if: ${{ inputs.skip-pr == 'false' }}
      uses: peter-evans/create-pull-request@v7
      with:
        branch: edgetest-patch
        base: ${{ inputs.base-branch }}
        delete-branch: true
        title: Changes by run-edgetest action
        commit-message: '[edgetest] automated change'
        body: Automated changes by [run-edgetest-action](https://github.com/edgetest-dev/run-edgetest-action) GitHub action
        add-paths: |
          requirements.txt
          setup.cfg
          pyproject.toml
