name: 'Run edgetest'
description: 'Run edgetest on your Python package'
inputs:
  edgetest-flags:  # id of input
    description: 'Options to pass to edgetest'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - run: echo Running edgetest with the following options ${{ inputs.edgetest-flags}}.
      shell: bash
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        channels: conda-forge
    - name: Install edgetest and edgetest-conda
      shell: bash -l {0}
      run: |
        conda install edgetest edgetest-conda
    - run: echo  ${{ pwd }}.
      shell: bash
    - name: Run edgetest
      shell: bash -l {0}
      run: |
        edgetest ${{ inputs.edgetest-flags}}